version: '3'

services:
  app:
    build: .
    restart: on-failure
    command: sh -c "npm run knex:migrate:latest && npm start"
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    depends_on:
     - postgres
    networks: 
     - restaurants-network
  postgres:
    image: postgres:alpine
    env_file: .env
    environment:
      - POSTGRES_USER=${APP_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_NAME}
    restart: always
    volumes:
      - ./postgres:/data/postgres
    ports:
      - ${APP_DB_PORT}:${APP_DB_PORT}
    networks:
      - restaurants-network
networks:
  restaurants-network:
    driver: bridge